# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 22) do

  create_table "analyses", :force => true do |t|
    t.column "chromosome",        :string
    t.column "start",             :integer
    t.column "end",               :integer
    t.column "taxon_id",          :integer
    t.column "session_id",        :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "primary_strain_id", :integer
  end

  create_table "genotypes", :force => true do |t|
    t.column "strain_id",        :integer
    t.column "is_het",           :boolean
    t.column "size",             :integer
    t.column "genotype_code",    :integer
    t.column "genotype_allele",  :string
    t.column "genotypable_id",   :integer
    t.column "genotypable_type", :string
  end

  add_index "genotypes", ["strain_id"], :name => "genotypes_strain_id_index"
  add_index "genotypes", ["genotypable_id"], :name => "genotypable_id"
  add_index "genotypes", ["genotypable_type"], :name => "genotypable_type"
  add_index "genotypes", ["genotypable_type"], :name => "genotypable_type_2"

  create_table "map_positions", :force => true do |t|
    t.column "map_id",            :integer
    t.column "chromosome_number", :integer
    t.column "chromosome_label",  :string
    t.column "strand",            :integer
    t.column "mappable_id",       :integer
    t.column "mappable_type",     :string
    t.column "start",             :integer
    t.column "end",               :integer
  end

  add_index "map_positions", ["map_id"], :name => "map_positions_map_id_index"
  add_index "map_positions", ["chromosome_number"], :name => "chromosome_number"
  add_index "map_positions", ["start"], :name => "start"

  create_table "maps", :force => true do |t|
    t.column "name",     :string
    t.column "map_type", :string
    t.column "version",  :string
    t.column "units",    :string
  end

  create_table "markers", :force => true do |t|
    t.column "symbol",              :string
    t.column "marker_type",         :string
    t.column "rgd_id",              :string
    t.column "dbsnp_id",            :string
    t.column "dbsts_id",            :string
    t.column "target_allele",       :string
    t.column "number_of_alleles",   :integer
    t.column "sequence",            :text
    t.column "bn_genotype",         :string
    t.column "reference_sslp_size", :integer
    t.column "ensembl_id",          :string
  end

  add_index "markers", ["rgd_id"], :name => "markers_rgd_id_index"
  add_index "markers", ["symbol"], :name => "symbol"
  add_index "markers", ["ensembl_id"], :name => "index_markers_on_ensembl_id"

  create_table "panel_markers", :force => true do |t|
    t.column "marker_id", :integer
    t.column "panel_id",  :integer
  end

  create_table "panels", :force => true do |t|
    t.column "name",              :string
    t.column "description",       :text
    t.column "taxon_id",          :integer
    t.column "manufacturer",      :string
    t.column "manufacturers_url", :string
  end

  create_table "populations", :force => true do |t|
    t.column "symbol",      :string
    t.column "name",        :string
    t.column "description", :text
    t.column "species",     :string
    t.column "taxon_id",    :integer
  end

  create_table "regions", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :integer
    t.column "chromosome_index", :integer
    t.column "map_id",           :integer
    t.column "flank1_marker_id", :integer
    t.column "flank2_marker_id", :integer
  end

  add_index "regions", ["flank1_marker_id"], :name => "regions_flank1_marker_id_index"
  add_index "regions", ["flank2_marker_id"], :name => "regions_flank2_marker_id_index"

  create_table "selected_strains", :force => true do |t|
    t.column "analysis_id",    :integer
    t.column "strain_id",      :integer
    t.column "position",       :integer
    t.column "analysis_group", :integer
  end

  create_table "strains", :force => true do |t|
    t.column "symbol",        :string
    t.column "mdc_id",        :string
    t.column "cng_id",        :string
    t.column "rgd_id",        :string
    t.column "origin",        :string
    t.column "origin_lab",    :string
    t.column "source_tissue", :string
    t.column "taxon_id",      :integer
    t.column "population_id", :integer
  end

  add_index "strains", ["mdc_id"], :name => "strains_mdc_id_index"
  add_index "strains", ["rgd_id"], :name => "strains_rgd_id_index"

  create_table "trait_measurements", :force => true do |t|
    t.column "strain_id", :integer
    t.column "trait_id",  :integer
    t.column "value",     :float
  end

  create_table "traits", :force => true do |t|
    t.column "code",        :string
    t.column "name",        :string
    t.column "description", :string
    t.column "units",       :string
  end

end
